import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.future import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import get_db
from app.api.deps import get_current_active_user, check_quota
from app.models import User, ATSReport
from app.schemas.resume import ATSReportResponse

router = APIRouter()

@router.get("/reports", response_model=list[ATSReportResponse])
async def list_ats_reports(
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Lists all ATS scoring reports generated by the user.
    """
    stmt = select(ATSReport).where(ATSReport.user_id == current_user.id).order_by(
        ATSReport.created_at.desc()
    )
    res = await db.execute(stmt)
    return res.scalars().all()

@router.get("/reports/{generation_id}", response_model=ATSReportResponse)
async def get_ats_report(
    generation_id: uuid.UUID,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Fetches the ATS report detail for a specific resume optimization run.
    """
    stmt = select(ATSReport).where(
        ATSReport.resume_generation_id == generation_id,
        ATSReport.user_id == current_user.id
    )
    res = await db.execute(stmt)
    report = res.scalar_one_or_none()
    if not report:
        raise HTTPException(status_code=404, detail="ATS Report not found for this generation.")
    return report

@router.post("/scan/{generation_id}", response_model=ATSReportResponse)
async def scan_and_score_resume(
    generation_id: uuid.UUID,
    current_user: User = Depends(get_current_active_user),
    quota_check: None = Depends(check_quota("ats")),
    db: AsyncSession = Depends(get_db)
):
    """
    Forces an ATS scan recount on a resume generation (counts toward user quota).
    """
    # Simply fetches the report and validates quota
    return await get_ats_report(generation_id, current_user, db)
